language: node_js
notifications:
  email: false
sudo: false
node_js:
  - "4.8.1"
cache:
  directories:
    - node_modules

before_install:
  - pushd /home/travis/build/BenJuan26
  - git clone https://github.com/EDCD/coriolis-data.git
  - popd

before_script:

script:
  - npm run lint
  - npm test
